### ISSUE TITLE
.btn-pseudo-states doesn't exists

### ISSUE THREAD

**Issue by geoom** [lipis/bootstrap-social#1]
In bootstrap3 doesn't exists the mixin .btn-pseudo-states() (line 20 on bootstrap-social-3.less) that's why the console throws an error to at moment to compile the file bootstrap-social-3.less, so it seems to me that it right to use .button-variant() instead of .btn-pseudo-states().

good library (y) !

**Comment by lipis** [comment]
It's fixed now.. thank you! I haven't touched for quite some time but now it's up to date...
