### ISSUE TITLE
Justified buttons

### ISSUE THREAD

**Issue by samdunne** [lipis/bootstrap-social#10]
Is there any quick way of putting these is a group and making it spread evenly across a div?

**Comment by lipis** [comment]
Something like that: http://jsfiddle.net/aHs8J/1/ (resize to bigger screen to see them aligned..)

If you don't want to collapse into stack change the divs to `col-xs-*` and they will always going to be aligned..

**Comment by lipis** [comment]
That's the idea at least of course you can have your own divs and justify them as you like.. I'm just showing the fact that the buttons are quite flexible and support these kind of things..

**Comment by lipis** [comment]
@samdunne Does the above solves your problem? Otherwise you'll have to be more specific on what you want..

**Comment by samdunne** [comment]
Not exactly. I was meaning so buttons would sit like this: http://getbootstrap.com/components/#btn-groups-justified

**Comment by lipis** [comment]
Actually the way I did the buttons they are reacting the same way as normal buttons in Bootstrap.. so yes it very doable without changing anything.. just following the Bootstrap's convention:

http://jsfiddle.net/aHs8J/3/

**Comment by samdunne** [comment]
Doesn't seem to work for me :/

https://www.dropbox.com/s/qmndv45jzveq34y/Screenshot%202014-01-29%2014.04.55.png

Possibly a Firefox bug

**Comment by lipis** [comment]
Chrome & Safari work nicely.. Firefox does something "stupid"... If you find the cause of error would be nice.. I'll be able to spend some time with it later this week..!

**Comment by samdunne** [comment]
I'll look into it :)

**Comment by lipis** [comment]
It looks like Firefox has issues with the `display: table-cell;` with a combination of `position:relative` and `position: absolute;` trick.. :(

**Comment by samdunne** [comment]
http://wisercoder.com/firefox-displaytable-cell-and-absolute-positioning/

Looks like a possible solution, unsure how you'd implement it cleanly

**Comment by lipis** [comment]
Stupid Firefox.. with a small fix I could fix the icons only justified buttons if you're happy with them you can use that (where the line-height depends on your theme):

```
.btn-social-icon :first-child {
  position: relative;   
  line-height: 32px;
}
```

http://jsfiddle.net/aHs8J/5/

**Comment by lipis** [comment]
@samdunne Did you solve this one anyhow?
