### ISSUE TITLE
conflict with dropmenu

### ISSUE THREAD

**Issue by shaunthegeek** [lipis/bootstrap-social#101]
put bootstrap-social into a dropmenu, the padding and color will conflict.

![2016-01-28 15-24-24](https://cloud.githubusercontent.com/assets/4971414/12637853/6a510a8c-c5d3-11e5-8a30-7eaa7f6f50b9.png)

**Comment by lipis** [comment]
It's not meant to be inside the dropdown menu and I don't think that I will support this out of the box..
