### ISSUE TITLE
How to extend boostrap-social.css?

### ISSUE THREAD

**Issue by amcsi** [lipis/bootstrap-social#108]
How am I meant to extend bootstrap-social.scss? I'm trying to create a stack-overflow social icon, but the buttons are appearing with transparent backgrounds, black font color, and the texts hovering over the icons.

This is my scss code:

``` scss
@import '~bootstrap-sass/assets/stylesheets/_bootstrap.scss';
@import '~bootstrap-social/bootstrap-social.scss';

.btn-stack-overflow {
  @include btn-social(#f86b23);
}
```

**Comment by lipis** [comment]
you have to compile it with something to generate the CSS.. but if you are thinking of updating the css for this project in order to include the SO.. then you don't have to waste your time..

**Comment by amcsi** [comment]
Gosh, what's with the attitude?
Yes, I'm using webpack with sass-loader to generate the CSS. The CSS is generated, but I'm not getting the result I'm expecting.
And no, I'm not intending to update this project -.-

**Comment by lipis** [comment]
I don't get why people are getting mad.. don't waste your time to generate the CSS.. https://github.com/lipis/bootstrap-social#pull-requests

Plus if you really wanted help.. it's the first time that you are referring to webpack and sass-loader.. there are hundreds of different ways of compiling stuff to CSS.. how are we supposed to know how to help?

**Comment by amcsi** [comment]
I'm actually learning on how to use a variety of frontend tools, and one of the things I'm learning now is SASS.

One way you could help is could you please let me know how you are generating the CSS file based on the SASS file? Just trying to load it results in an error that it demands bootstrap-sass's variables and button mixin; but when I provide those, or the entire bootstrap.scss for that matter, the result looks bad like I described in the issue.

**Comment by lipis** [comment]
I'm generating it using [Less](http://lesscss.org/)

**Comment by amcsi** [comment]
I see.

May I ask in what order do you "import" variables and anything else from the bootstrap project and also your own bootstrap-social.less file to result in the compiled bootstrap-social.css file? I would like to do something similar, but with your scss file. Like you can see in the code example in the issue, I'm trying to use your scss file so I can use your btn-social mixin

**Comment by lipis** [comment]
In theory if you are loading the whole [thing](https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/_bootstrap.scss).. it should work.. here is an example of something similar in [Less](https://github.com/gae-init/gae-init/blob/master/main/static/src/style/style.less#L9)..

**Comment by amcsi** [comment]
Ok that indeed worked; the problem was that I was already loading bootstrap at my outermost composent, and again in a different scss file for the purposes of using the variables for bootstrap-social. I have yet to find out how exactly I'm supposed to use css together with webpack.
Thanks!

**Comment by lipis** [comment]
StackOverflow  is one way to find out if you are already searched the whole internet :)

**Comment by amcsi** [comment]
I was actually searching resources on how exactly style loading works in webpack, and I had trouble finding resources on it

**Comment by lipis** [comment]
http://stackoverflow.com/questions/ask
