### ISSUE TITLE
Can't align them horizontally 

### ISSUE THREAD

**Issue by Netman82** [lipis/bootstrap-social#114]
Hi,

I Added 3 Icons to a col-md-4 and still have room almost as twice of the three icons.
But they don't get aligned horizontally.

```
<div class="social">
                                    <a class="btn btn-block btn-social-icon btn-facebook">
                                        <span class="fa fa-facebook"></span>
                                    </a>
                                     <a class="btn btn-block btn-social-icon btn-twitter">
                                        <span class="fa fa-twitter"></span>
                                    </a>
                                     <a class="btn btn-block btn-social-icon btn-linkedin">
                                        <span class="fa fa-linkedin"></span>
                                    </a>
</div>
```

"Social" class just does "text-align:center"
No parent class is set to have alignment.

They get aligned vertically (at the bottom of each other).

What should I do?

Thanks

**Comment by lipis** [comment]
can you have a JSFiddle with your issue?

**Comment by Netman82** [comment]
Here it is:
[Fiddle](https://jsfiddle.net/qj8w4Lq4/2/)
Removed "Social" class and added "Text-center" - does the same.

**Comment by lipis** [comment]
https://jsfiddle.net/qj8w4Lq4/4/ You have to remove the `btn-block`..

**Comment by Netman82** [comment]
Damn ! 
I didn't notice that.
Thanks bro
