### ISSUE TITLE
update dependencies

### ISSUE THREAD

**Issue by pherum** [lipis/bootstrap-social#116]
Hello. Please, update package dependencies.

_bower.json_

```
  "dependencies": {
    "bootstrap": "~3",
    "font-awesome": "~4"
  }
```

_package.json_

```
  "dependencies": {
    "bootstrap": "~3",
    "font-awesome": "~4"
  }
```

**Comment by lipis** [comment]
If you feel like editing the files right away and issuing a PR would be awesome..

**Comment by pherum** [comment]
yes of course, it's understandable. Unfortunately at the moment I have no way to do PR
and an indication of major dependencies will always download the current version of the font icon and this issue is no longer relevant)

**Comment by lipis** [comment]
So I'm not sure... do you want it or not?

**Comment by pherum** [comment]
sorry for my English. I use Google Translate.
please update dependencies)

**Comment by lipis** [comment]
Tы можешь и по русский если хочешь..

**Comment by pherum** [comment]
@lipis спасибо, поржал)))

обнови пожалуйста пакеты зависимостей для font-awesome указав мажорную версию, чтобы избежать постоянных конфликтов в пакетных менеджерах.
в данном репозитории это можно сделать.

извини, но PR в ближайшее время отправить не могу, так бы конечно же сделал PR.

P.S. если не сложно, добавьте еще Yandex иконку. (но думаю лучше будет написать отдельный issue для этой хотелки)

**Comment by lipis** [comment]
:D Will do later.. while I understand russian it's hard to type it for me :) I'll update it eventually..  and as for Yandex I want to refactor the whole thing to start adding all of the requested ones in a separate file.. one of these days... :)

**Comment by ssteinerx** [comment]
A release with the ~4.6.0 font-awesome dependency (the way it is on master) would be awesome as it would remove a 4.5.x vs 4.6.x conflict with several other things I'm using.
