### ISSUE TITLE
Styling errors

### ISSUE THREAD

**Issue by lorensr** [lipis/bootstrap-social#12]
Hi, I've added bootstrap and font awesome, and added bootstrap-social.css from the root of the repo. I then added the example HTML, and got this:
![screen shot 2014-02-22 at 10 23 28 pm](https://f.cloud.github.com/assets/251288/2239509/23545c48-9c3a-11e3-9d20-9489e94e1e6d.png)

Am I using the wrong .css file? I didn't see a /css folder as instructed in step 2 of http://lipis.github.io/bootstrap-social/

**Comment by lipis** [comment]
I will have to update the instructions.. But if you download the whole project as is.. and open the index.html do you see the buttons?

**Comment by lorensr** [comment]
Yes, that works, thanks - I'll figure out what my server is doing differently.

**Comment by lipis** [comment]
good luck
