### ISSUE TITLE
package.json.main should not point to a css file

### ISSUE THREAD

**Issue by istrau2** [lipis/bootstrap-social#122]
Please see this issue for more details: https://github.com/aurelia/webpack-plugin/issues/71

**Comment by lipis** [comment]
where should it point to then?

**Comment by niieani** [comment]
No `main` should be present in this case, as that's reserved for JS files only. 
Instead, you can use a `css` property  (if I remember correctly) which can point to the main CSS file.

**Comment by niieani** [comment]
Why was this closed without a fix?

**Comment by niieani** [comment]
I've sent a PR with a fix.
