### ISSUE TITLE
saas file isn't compiling

### ISSUE THREAD

**Issue by musharrafkhan** [lipis/bootstrap-social#128]
when i try to compile .scss file it gives an error " undifine variable $line-height-computed "

**Comment by lipis** [comment]
are  you including the Bootstrap source files?

**Comment by musharrafkhan** [comment]
yes through CDN link i am including both css and js files of bootstrap

**Comment by lipis** [comment]
well.. here is your answer :)

**Comment by musharrafkhan** [comment]
sorry i didn't understand

**Comment by lipis** [comment]
Yes.. if you are using SASS files to compile then you need to use Bootstrap source files.. and not the compiled ones as the `$line-height-computed` is coming from Bootstrap dependency..

**Comment by musharrafkhan** [comment]
Got it thank you so much 👍 👍

**Comment by sethi2307** [comment]
I am still not able to figure out what you mean when you say :are you including the Bootstrap source files?
