### ISSUE TITLE
Bootstrap destroys entire style of existig websites.

### ISSUE THREAD

**Issue by thewhiterabbit** [lipis/bootstrap-social#130]
I was excited to see these cool CSS login buttons, until I applied them in the real world. As everyone knows, bootstrap is a no-no because of it's bad practice, weight, difficulty to customize, etc.. I though, maybe, these buttons could work stand-alone. Nope.

If these would work for existing projects as a drop-in solution, without bootstrap, great, but requiring bootstrap is like opening an ice cream shop and only selling a horrible tasting vanilla with amazing sprinkles.

**Comment by lipis** [comment]
I don't know if you noticed.. but the project is called `bootstrap-social` didn't that gave a couple of clues that it might require Bootstrap to work with?!

Also as _everyone knows_ people that can't read or they assume things that shouldn't assume won't make it far in their life..
