### ISSUE TITLE
Bootstrap destroys entire style of existig websites.

### ISSUE THREAD

**Issue by thewhiterabbit** [lipis/bootstrap-social#131]
It's OK though. It only took me a few hours to build this from scratch WITHOUT hideous Bootstrap. I would give you a pull, but since you wanted to personally insult me, no. I was actually complimenting your efforts, and simply nudging you to detach from the Bootstrap requisite. Sorry I offended you by down-talking your beloved Bootstrap. Cheers.

**Comment by lipis** [comment]
Internet is a funny place..

**Comment by lipis** [comment]
> but requiring bootstrap is like opening an ice cream shop and only selling a horrible tasting vanilla with amazing sprinkles.

So do you think still that I insulted you..?!

Flash news: I'm not requiring anything.. it's a free fucking world.. RTFM and take it from there..

**Comment by thewhiterabbit** [comment]
Well... you do have beautiful sprinkles (the buttons + FA), but the Bootstrap requirement is VERY debilitating. I think you can see that, you seem to be well experienced. If it were to work with OR without Bootstrap, just think of how many tens of thousands of more people would want to use it.

**Comment by lipis** [comment]
there are better ways to address the issue without having the stupid/immature attitude like: _"As everyone knows, bootstrap is a no-no because of it's bad practice"_ for something that has 100K followers, etc, etc.. so learn how the world works first and then start making these statements..
