### ISSUE TITLE
Create Ravelry/Etsy/Craftsy buttons

### ISSUE THREAD

**Issue by hellboy81** [lipis/bootstrap-social#147]
See [Crafty-Social-Buttons](http://sarahhenderson.github.io/Crafty-Social-Buttons/)

- [ravelry](http://fontawesome.io/icon/ravelry/)
- [etsy](http://fontawesome.io/icon/etsy/)

**Comment by hellboy81** [comment]
Raverly Button: 

![ravelry](https://cloud.githubusercontent.com/assets/341600/23096920/67543554-f627-11e6-9040-2a1144956c04.png)

Etsy Button:

![etsy](https://cloud.githubusercontent.com/assets/341600/23096927/83fb2668-f627-11e6-9c14-45217610781c.png)

Craftsy Button:

![craftsy](https://cloud.githubusercontent.com/assets/341600/23096931/c65ebe2a-f627-11e6-80c9-da8ea12fa522.png)

**Comment by lipis** [comment]
icons are not part of this repo..
