### ISSUE TITLE
CDN

### ISSUE THREAD

**Issue by fulldecent** [lipis/bootstrap-social#16]
Please host on CDN if possible

**Comment by jimaek** [comment]
Here you go http://www.jsdelivr.com/#!bootstrap.social

You can even build a URL with all dependencies and load it with a single HTTP request. 
For example: `http://cdn.jsdelivr.net/g/bootstrap@3.1(css/bootstrap.min.css),bootstrap.social`

**Comment by lipis** [comment]
hm.. I don't like the dot in the name.. can we change that so it is consistent?

**Comment by jimaek** [comment]
Its a plugin for bootstrap, right? For example main library is jquery so the plugin will be jquery.cookie, 

I am trying to follow the same structure. If you dont agree I can rename it but I would prefer to keep it this way.

**Comment by lipis** [comment]
I can understand why and yes that's how the jQuery does it but because everywhere else is with the dash I think I would prefer to keep it consistent and I can see that there are already couple of them that are like that in the list :)

So can we keep it as the original name?! :dancer:

**Comment by jimaek** [comment]
Per your request I renamed the project. Old files will still remain on the origin so if someone is using the current name his website wont break.

http://www.jsdelivr.com/#!bootstrap-social

**Comment by lipis** [comment]
Awesome man.. thanks..!

Wasn't aware of the project.. I wonder who is paying for all that?!

**Comment by jimaek** [comment]
Actually today a blog post of mine went viral and you read all about jsDelivr over here https://news.ycombinator.com/item?id=7428803

Let me know if I can help you with anything else :)

**Comment by lipis** [comment]
Read already the about page as well... Nice job..!! Good luck man...

**Comment by lipis** [comment]
I will update eventually my README to include this links as well..

**Comment by jimaek** [comment]
Awesome, ping me if you need anything
