### ISSUE TITLE
don't work google

### ISSUE THREAD

**Issue by juanitourquiza** [lipis/bootstrap-social#163]
This code don't work:
```
 <a class="btn btn-social-icon btn-facebook" href="login/facebook">
  <span class="fa fa-facebook"></span>
 </a>
 <a class="btn btn-social-icon btn-google" href="login/google">
   <span class="fa fa-google"></span>
 </a>
```
This is the result:
![rr](https://user-images.githubusercontent.com/332299/31298588-6e958f1e-aab0-11e7-8031-9ba8ccfd9735.png)

What is the problem??

**Comment by Pandalousie** [comment]
I think your font-awesome file (css) is a bad version ! Test with "font-awesome": "~4.7"

**Comment by juanitourquiza** [comment]
Thanks !!!! Now, it's perfect

Regards
