### ISSUE TITLE
No Social Badges

### ISSUE THREAD

**Issue by cyb3rgh05t** [lipis/bootstrap-social#167]
Hey,

I have a little issue. The social badges arent showing up in my projet.

![f38e2145-601c-4c91-bcec-9161f9bfd662](https://user-images.githubusercontent.com/5200101/34456851-2d6b72cc-eda1-11e7-8c78-0137950e53ce.png)

Do you know what it could be?

Thanks a lot, awesome work :)

**Comment by bhvk** [comment]
same is the case with me did you find a solution @Cyb3rGh05t

**Comment by bhvk** [comment]
Hey @Cyb3rGh05t I guess I found the issue, you must have not used the "FontAwesome" icon toolkit. bootstrap-social works on it.
Here's the CDN of free version  :+1: 
`<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.9/css/all.css" integrity="sha384-5SOiIsAziJl6AWe0HWRKTXlfcSHKmYV4RBF18PPJ173Kzn7jzMyFuTtk8JA7QQG1" crossorigin="anonymous">`

**Comment by lipis** [comment]
yep.. the icons are not part of the project
