### ISSUE TITLE
Implementation w/o Requiring Bootstrap

### ISSUE THREAD

**Issue by adrianmcli** [lipis/bootstrap-social#2]
Any chance of having this standalone w/o needing to include bootstrap? Thanks!

**Comment by lipis** [comment]
To achieve that.. I would simply include the Bootstrap stuff in one `.less` file and probably call it `no-bootstrap-social.less`.. is that ok?

**Comment by lipis** [comment]
I think I'll drop this one.. it doesn't make much sense to copy all the dependencies for the buttons from bootstrap just to make it Bootstrapless, something that is called bootstrap-social :)
