### ISSUE TITLE
btn-youtube

### ISSUE THREAD

**Issue by magnusburton** [lipis/bootstrap-social#20]
Please add a Youtube button with the fa-youtube icon or (alternatively fa-youtube-play)

**Comment by lipis** [comment]
You can't really sign in with YouTube.. is a Google login :) I understand that you might want it for sharing or something.. but at one point we'll have to draw a line.. since it's very very easy to extend it if you're using .less or .sass by adding one line..

**Comment by magnusburton** [comment]
Oh okay I see, thank you anyways! :)
