### ISSUE TITLE
Lanyrd Icon

### ISSUE THREAD

**Issue by carlwood** [lipis/bootstrap-social#21]
Brilliant work!

Any chance of a lanyrd (http://lanyrd.com/) icon? It's the one that's always missing from a font kit/ web font.

**Comment by lipis** [comment]
Well not really to the core project.. because it doesn't really exist in Font Awesome.. but you can find it (http://fontello.com/#search=lanyrd) and use it with this project.. it shouldn't be a problem!

**Comment by carlwood** [comment]
Good point! I'll get onto FA in the mean time :panda_face:
