### ISSUE TITLE
Bower font-awesome shouldn't be required

### ISSUE THREAD

**Issue by jasny** [lipis/bootstrap-social#25]
Currently you have font-awesome as a requirement when installing bootstrap-social using bower. However bootstrap-social will also work nicely with any other icon set like [Socicon](http://socicon.com/) or [Elusive icons](http://shoestrap.org/downloads/elusive-icons-webfont/).

Please put font-awesome in the [devDependencies](http://bower.io/docs/creating-packages/) section intead.

**Comment by lipis** [comment]
you're right.. you can submit a PR if you like..
