### ISSUE TITLE
Problems with Bootstrap 3

### ISSUE THREAD

**Issue by shashu10** [lipis/bootstrap-social#29]
Shadows and background images cause UI problems in Bootstrap 3.

You can add the line to get the desired appearance:

```
.btn{text-shadow:none;background-image:none;-webkit-box-shadow:none;box-shadow:none}
```

**Comment by lipis** [comment]
Well none of these properties are actually used in Bootstrap 3 as you can see here: https://github.com/twbs/bootstrap/blob/v3.2.0/less/buttons.less nor in this project.. so I don't see any point of actually including these properties..

**Comment by shashu10** [comment]
My bad. I was using a modified bootstrap.
