### ISSUE TITLE
Why is Font Awesome a dev dependency?

### ISSUE THREAD

**Issue by reggi** [lipis/bootstrap-social#31]

**Comment by lipis** [comment]
I think it was there because you can use any other icons library

**Comment by reggi** [comment]
I expected to see it in there as a dependency, all of your examples come with it, It's necessary for the social part to have those social icons. In my project polymer component it's using both `bootstrap-social` and `font-awesome` as deps here's the [bower.json](https://github.com/reggi/polymer-bootstrap-social/blob/master/bower.json). I totally understand though!

**Comment by lipis** [comment]
I'm on vacations now but I will fix that when I'm back.. or you can create a PR..

I was also thinking about creating a polymer component for it, just started playing with it.. so I might get some ideas from you! Thanks
