### ISSUE TITLE
Bootstrap Social Buttons issue with Bootstrap Split Button Drop Downs

### ISSUE THREAD

**Issue by mgildea** [lipis/bootstrap-social#32]
Using the split button drop down example provided by bootstrap:
http://getbootstrap.com/components/#btn-dropdowns-split

split portion of drop down is not displayed properly when setting the class of both buttons in the bootstrap example to:

"btn btn-block btn-social btn-facebook".

or other combinations of css classes with the two buttons.  I did not see any css for btn-group within your bootstrap-social.css.

this would be great if your project was fully usable with bootstrap.  

Thanks for keeping up this cool project.

**Comment by lipis** [comment]
Never thought of that one.. how would you use the social sharing button with the dropdown?! What's the use case?

**Comment by mgildea** [comment]
I have a user login mgmt page to change local password, associate social logins with local account, and to disassociate social logins.  So when a social logins button is clicked, it logs in with that provider and links to the local account.  IF the user already has that social login service associated with their local account a drop down is available with the option to "disassociate".  see attached image of the display issues between this project and the button drop down functionality with bootstrap.

![bootstrap social issue](https://cloud.githubusercontent.com/assets/2811551/3954400/fcf487d4-26f5-11e4-9a7d-42f71650da78.PNG)

**Comment by lipis** [comment]
Yes I got it.. :) Thanks.. I will take a look at one point and leave that issue open.. as I'm a bit busy these days it will have to wait..

**Comment by ghost** [comment]
I wish this function could be built too
