### ISSUE TITLE
Issue with spin icons

### ISSUE THREAD

**Issue by AlexeyKosov** [lipis/bootstrap-social#34]
If put some spin icon instead of social icon (e.g. after button is clicked), right border of icon is rotating with the icon.

[a class="btn btn-block btn-social btn-facebook"]
[i class="fa fa-spinner fa-spin"][/i] Sign in with Facebook
[/a]

**Comment by lipis** [comment]
Yeap :) That would happen if you rotate the element that has the border..
https://github.com/lipis/bootstrap-social/blob/gh-pages/bootstrap-social.less#L31

I just [updated it](https://github.com/lipis/bootstrap-social/commit/79063cd82cd181a64c88c2a06665475ace6a1f84) so it will affect only the direct first child... so you could use something like that to have the icon rotated...

``` html
<a class="btn btn-block btn-social btn-twitter">
  <div><i class="fa fa-twitter fa-spin"></i></div>
  Sign in with Twitter
</a>
```

http://jsbin.com/gojap/6/

**Comment by lipis** [comment]
It doesn't work nicely with the `btn-lg`  but you can take it from there and override the `font-size` or whatever you want for your own special case..

**Comment by AlexeyKosov** [comment]
Thanks, I'll try this way!
