### ISSUE TITLE
download failed: fontawesome-webfont.ttf

### ISSUE THREAD

**Issue by sistemisolarirossi** [lipis/bootstrap-social#37]
Probably not a bootstrap-social issue, but...
When I test locally, I have no issue.
After deploying (to gh-pages), social icons are not rendered because fontawesome web fonts were not uploaded...
Any hint about the grunt config for this small issue?

**Comment by lipis** [comment]
Just include them in the repo.. not sure I understood your problem.. if everything works locally it should work..

**Comment by sistemisolarirossi** [comment]
Yes, thanks. Problem solved.
