### ISSUE TITLE
Request: Steam

### ISSUE THREAD

**Issue by barratt** [lipis/bootstrap-social#47]
Not so much the sign in, but a button that matches the theme of the others would be nice for linking my steam profile on my website :D

**Comment by lipis** [comment]
Are you using Less?! If so.. just add a new button by choosing the right color.. https://github.com/lipis/bootstrap-social/blob/gh-pages/bootstrap-social.less#L95-L114

**Comment by lipis** [comment]
I want to split the core from the rest and then maybe start adding more buttons.. but at the moment I already have too many for the core functionality..

**Comment by barratt** [comment]
No worrys, I have a basic thing setup with some custom CSS anyway. I appreciate your effort with making this project. And thank you @Francismori7

**Comment by patvdleer** [comment]
What happened to Steam? I don't see it in the current version

**Comment by lipis** [comment]
If you guys using Less or SASS then it's super easy to just change the color and add the icon that is not part of this library anyway.. and if you're not using Less or SASS.. then you should :)

**Comment by patvdleer** [comment]
I did it oldskool, css quick mod, but I was wondering why the commit made by @Francismori7 isn't accepted and merged? I can imagine it now being outdated but it seems simply to adjust it to the current version.
