### ISSUE TITLE
Sass support

### ISSUE THREAD

**Issue by azachar** [lipis/bootstrap-social#49]
Hello!

I am trying to use your library for https://github.com/DaftMonk/generator-angular-fullstack/issues/640
but I cannot find any sass version. Is there any sass fork?

Thank you for your help!

Best regards,
Andrej

**Comment by lipis** [comment]
That's all I have: https://github.com/lipis/bootstrap-social/blob/gh-pages/bootstrap-social.scss

**Comment by azachar** [comment]
Thank you for you response. I try to use it:)

**Comment by azachar** [comment]
Yep, it works nice, btw do you support stylus too?

**Comment by lipis** [comment]
it should work if you are using bootstrap  and it's variables.. the whole idea is that it will match exactly the normal btn buttons

**Comment by lipis** [comment]
No Stylus support..
