### ISSUE TITLE
Amazon Login button

### ISSUE THREAD

**Issue by ltagliamonte** [lipis/bootstrap-social#52]
Hi!
very nice job can you add also login with Amazon button?
Thanks.
L.

**Comment by hephaestoskin** [comment]
I agree, especially since it could be used for amazon checkout.

**Comment by rentrop** [comment]
Yeah, i totally agree

**Comment by idmontie** [comment]
There is an Amazon font awesome icon, so this would make sense: `<i class="fa fa-amazon"></i>`

**Comment by OpaVote** [comment]
+1
