### ISSUE TITLE
Add whatsapp button

### ISSUE THREAD

**Issue by devilankur18** [lipis/bootstrap-social#56]

**Comment by mohsin** [comment]
I don't think you can login with whatsapp so it wouldn't be a good idea to add a Login with Whatsapp button. Anyway I made a repo for [whatsapp](https://github.com/SaifurRahmanMohsin/Whats-Awesome) icon. You could use this but it's not for login.

**Comment by omarcumx** [comment]
Para mi si es escencial por que quiero que la gente entre a mi página y pueda enlazarse conmigo mediante agregarse a un grupo de whatsapp
