### ISSUE TITLE
Google / google-plus

### ISSUE THREAD

**Issue by stijnhau** [lipis/bootstrap-social#57]
i propose using the adding google class to the css.
Just the same as google-plus but with other nbame because mostly google is set as the provider and not google plus.

**Comment by lipis** [comment]
The reason that I have google-plus is because it all started with the same exactly _code_ as with Font Awesome.. But maybe you're right..

**Comment by lipis** [comment]
Fixed in https://github.com/lipis/bootstrap-social/commit/b53226d35592aa0169575e9e1b5f5c549a1145f3
