### ISSUE TITLE
Composer package

### ISSUE THREAD

**Issue by p2made** [lipis/bootstrap-social#63]
I'd like to suggest you bundle Bootstrap Social as a package for [Composer](https://getcomposer.org) & submit it to [Packagist](https://packagist.org).

The process is as simple as creating a `composer.json` file & submitting the GitHub URL on Packagist. If you also authorise Packagist in the GitHub project settings then your updates to Bootstrap Social automagically go to Packagist.

An example of a web assets package bundled like this is [metisMenu](https://github.com/onokumus/metisMenu), & on [Packagist](https://packagist.org/packages/onokumus/metismenu).

With Bootstrap Social bundled like this, any developer who declares it as a dependancy has it updated any time they run `composer update` on their project.

**Comment by lipis** [comment]
Can you create a PR for the `composer.json`?

**Comment by p2made** [comment]
I think I've just done that. :)
