### ISSUE TITLE
Npm repository is old

### ISSUE THREAD

**Issue by Ardakilic** [lipis/bootstrap-social#68]
Hello,

There's a npm repository in the npmjs.org

https://www.npmjs.com/package/bootstrap-social

I don't know if this is official and maintained by you or not, but if it is official, could you please take time to update this? If not, are there any plans to add this to npm as official repository?

Thanks in advance,

**Comment by lipis** [comment]
No it's not maintained by me.. I didn't add it there.. is it possible to remove the version from the `package.json` so it will get the releases, as it's happening with `bower.json`

**Comment by mathieumg** [comment]
> If not, are there any plans to add this to npm as official repository?

I would love npm releases too. Since you own the package, you can easily get the ownership back on npm.

**Comment by lipis** [comment]
How do I get ownership?

**Comment by mathieumg** [comment]
https://docs.npmjs.com/misc/disputes

@tbranyen probably didn't mean any harm when we took the name on npm, he just wanted it there while it wasn't. He'll probably transfer you ownership without opposition. :smile:

**Comment by lipis** [comment]
I already send an email to the owner of it.. of course there are no bad feelings or anything :) I'm actually flattered with those things.. :dancer:

**Comment by lipis** [comment]
I'm the owner now https://www.npmjs.com/package/bootstrap-social :+1: so the next question is how do I update it?

**Comment by mathieumg** [comment]
:tada: 

https://docs.npmjs.com/getting-started/creating-node-modules + https://docs.npmjs.com/getting-started/publishing-npm-packages should be more than enough!

For the `package.json`, you can always take great inspiration from your `bower.json`. You can even keep the same dependencies as they exist on npm as well:

``` js
"dependencies": {
  "bootstrap": "~3",
  "font-awesome": "~4.3"
}
```

Don't hesitate if you have questions or if you would rather I submit this as part of a PR. Thanks!

**Comment by lipis** [comment]
actually if you could submit a PR would be the best ATM :) Try to keep it as close to `bower.json` so it will be easier to maintain it later on..

**Comment by mathieumg** [comment]
Alright, I'll get on that!

**Comment by Ardakilic** [comment]
You guys are great, I was away for couple of hours and there is already progress on this, thanks! :clap: :dancer: :smile:

**Comment by lipis** [comment]
![typing](https://cloud.githubusercontent.com/assets/125676/7824972/003839c8-0408-11e5-8196-f60440503617.gif)

**Comment by mathieumg** [comment]
Once that is merged, you only need to do the https://docs.npmjs.com/getting-started/publishing-npm-packages part! :shipit:

**Comment by mathieumg** [comment]
@lipis Any news on this? :smile:
