### ISSUE TITLE
Update font-awesome to 4.4 and add odnoklassniki button

### ISSUE THREAD

**Issue by FractalizeR** [lipis/bootstrap-social#79]
Hello.

Could you do this?

OK button was added to 4.4: https://github.com/FortAwesome/Font-Awesome/issues/1685

**Comment by matyunin** [comment]
@FractalizeR, actually `OK` icon now has another (not like in PR you specified) class name: http://fortawesome.github.io/Font-Awesome/icon/odnoklassniki/

@lipis, Odnoklassniki (OK) is a popular russian social network. We use your lib and wait for FO 4.4 features implementation.

Thanks!

**Comment by matyunin** [comment]
lipis@f955e66260efab9ff4618a5e357bf8e3c34e69ab

**Comment by AndyHoang** [comment]
could you also update the package.json to 4.4 font-awesome?
