### ISSUE TITLE
Add Telegram button

### ISSUE THREAD

**Issue by theRuslan** [lipis/bootstrap-social#89]

**Comment by Netman82** [comment]
Add this to boostrap.social.css:

`.btn-telegram{color:#fff;background-color:#2AA5E0;border-color:rgba(0,0,0,0.2)}.btn-telegram:focus,.btn-telegram.focus{color:#fff;background-color:#1b88bc;border-color:rgba(0,0,0,0.2)}
.btn-telegram:hover{color:#fff;background-color:#1b88bc;border-color:rgba(0,0,0,0.2)}
.btn-telegram:active,.btn-telegram.active,.open>.dropdown-toggle.btn-telegram{color:#fff;background-color:#2AA5E0;border-color:rgba(0,0,0,0.2)}.btn-telegram:active:hover,.btn-telegram.active:hover,.open>.dropdown-toggle.btn-telegram:hover,.btn-telegram:active:focus,.btn-telegram.active:focus,.open>.dropdown-toggle.btn-telegram:focus,.btn-telegram:active.focus,.btn-telegram.active.focus,.open>.dropdown-toggle.btn-telegram.focus{color:#fff;background-color:#1b88bc ;border-color:rgba(0,0,0,0.2)}
.btn-telegram:active,.btn-telegram.active,.open>.dropdown-toggle.btn-telegram{background-image:none}
.btn-telegram.disabled,.btn-telegram[disabled],fieldset[disabled] .btn-telegram,.btn-telegram.disabled:hover,.btn-telegram[disabled]:hover,fieldset[disabled] .btn-telegram:hover,.btn-telegram.disabled:focus,.btn-telegram[disabled]:focus,fieldset[disabled] .btn-telegram:focus,.btn-telegram.disabled.focus,.btn-telegram[disabled].focus,fieldset[disabled] .btn-telegram.focus,.btn-telegram.disabled:active,.btn-telegram[disabled]:active,fieldset[disabled] .btn-telegram:active,.btn-telegram.disabled.active,.btn-telegram[disabled].active,fieldset[disabled] .btn-telegram.active{background-color:#1b88bc;border-color:rgba(0,0,0,0.2)}
.btn-telegram .badge{color:#3b5998;background-color:#fff}`

HTML Code:

`<a class="btn btn-social-icon btn-telegram">
                                    <span class="fa fa-paper-plane"></span>
                                </a>`

**Comment by viktorShatalov** [comment]
yeee

**Comment by toleeck** [comment]
if someone is looking for a set of styles for a whatsapp icon:
```css
.btn-whatsapp {
    color: #fff;
    background-color: #25d366;
    border-color: rgba(0, 0, 0, 0.2);
}
.btn-whatsapp:focus,
.btn-whatsapp.focus {
    color: #fff;
    background-color: #1da851;
    border-color: rgba(0, 0, 0, 0.2);
}
.btn-whatsapp:hover {
    color: #fff;
    background-color: #1da851;
    border-color: rgba(0, 0, 0, 0.2);
}
.btn-whatsapp:active,
.btn-whatsapp.active,
.open > .dropdown-toggle.btn-whatsapp {
    color: #fff;
    background-color: #25d366;
    border-color: rgba(0, 0, 0, 0.2);
}
.btn-whatsapp:active:hover,
.btn-whatsapp.active:hover,
.open > .dropdown-toggle.btn-whatsapp:hover,
.btn-whatsapp:active:focus,
.btn-whatsapp.active:focus,
.open > .dropdown-toggle.btn-whatsapp:focus,
.btn-whatsapp:active.focus,
.btn-whatsapp.active.focus,
.open > .dropdown-toggle.btn-whatsapp.focus {
    color: #fff;
    background-color: #1da851;
    border-color: rgba(0, 0, 0, 0.2);
}
.btn-whatsapp:active,
.btn-whatsapp.active,
.open > .dropdown-toggle.btn-whatsapp {
    background-image: none;
}
.btn-whatsapp.disabled,
.btn-whatsapp[disabled],
fieldset[disabled] .btn-whatsapp,
.btn-whatsapp.disabled:hover,
.btn-whatsapp[disabled]:hover,
fieldset[disabled] .btn-whatsapp:hover,
.btn-whatsapp.disabled:focus,
.btn-whatsapp[disabled]:focus,
fieldset[disabled] .btn-whatsapp:focus,
.btn-whatsapp.disabled.focus,
.btn-whatsapp[disabled].focus,
fieldset[disabled] .btn-whatsapp.focus,
.btn-whatsapp.disabled:active,
.btn-whatsapp[disabled]:active,
fieldset[disabled] .btn-whatsapp:active,
.btn-whatsapp.disabled.active,
.btn-whatsapp[disabled].active,
fieldset[disabled] .btn-whatsapp.active {
    background-color: #1da851;
    border-color: rgba(0, 0, 0, 0.2);
}
.btn-whatsapp .badge {
    color: #3b5998;
    background-color: #fff;
}
`
