### ISSUE TITLE
Bootstrap 4 support

### ISSUE THREAD

**Issue by Jonathan-Rosewood** [lipis/bootstrap-social#91]

**Comment by lipis** [comment]
once it's closer to the RC1 :)

**Comment by Jonathan-Rosewood** [comment]
@lipis okay, thanks for answer! :)
Still wait.

**Comment by Francismori7** [comment]
Reconsider?

**Comment by lipis** [comment]
Maybe.. 💃

**Comment by Francismori7** [comment]
@lipis I've got it to work properly myself on my own though.

![image](https://cloud.githubusercontent.com/assets/520647/15091957/49b8d8f0-1429-11e6-97a7-2a66ff7df00d.png)

**Comment by niftylettuce** [comment]
please add bootstrap 4 support!
