### ISSUE TITLE
Organize sources in subdirectories

### ISSUE THREAD

**Issue by nelson6e65** [lipis/bootstrap-social#93]
:art: 
Should be nice to have organized the sources and distributable files in separated directories, such as other libraries like Bootstrap, 

For example, serve the files in:
- **`sass/`**, for `.scss` sources;
- **`less/`**, for `.less` sources; and 
- **`dist/css/`**, for the compiled one (or simply **`css/`**).

Maybe dumping a new minor/major release after, since will break backward compatibility.

**Comment by lipis** [comment]
Yes.. didn't want to have directories because there is only one file per type... but maybe I'll split the files into more to have the basic ones in one and then then all.. so we can start adding as many new icons/colors as we want :) WDYT?

(the version will change for sure)

**Comment by nelson6e65** [comment]
Nice...

Yes, this will make easy publish via **gulp** or any other build tool.
