### ISSUE TITLE
.button-variant is not defined

### ISSUE THREAD

**Issue by manticorp** [lipis/bootstrap-social#96]
Hey, I tried including and compiling your less file, and I get an error related to the button-variant mixin not being defined in `bootstrap-social/bootstrap-social.less`.

Here's the offending code:

```
.btn-social(@color-bg, @color: #fff) {
  background-color: @color-bg;
  .button-variant(@color, @color-bg, rgba(0,0,0,.2));
}
```

before I try and reverse engineer what it was supposed to be from the css files, do you have it's definition anywhere?

**Comment by lipis** [comment]
As the name suggests.. it's based on Bootstrap.. so it assumes that you including it when working with source: https://github.com/twbs/bootstrap/blob/v3.3.6/less/mixins/buttons.less#L6

**Comment by manticorp** [comment]
Ah I see, sorry, my bad - feel free to close the issue!

**Comment by lipis** [comment]
np.. good luck.
