### ISSUE TITLE
Create bootstrap-sass branch to avoid conflicts with bootstrap

### ISSUE THREAD

**Issue by joaoqalves** [lipis/bootstrap-social#98]
Would it be possible to create a branch where the dependency on `bootstrap` is replaced by `bootstrap-sass-official`? I can do it and create the MR, but the branch should already exist so we can merge it back properly. Otherwise people that are using `bootstrap-sass-official` will need to deal with dependency exclusion in the build phase, which is not very elegant.

**Comment by lipis** [comment]
are you still interested in this one?
